---
- name: master_instance
  hosts: master
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  roles:
   - dockerSwarmMaster
- name: slave-node
  remote_user: ubuntu
  hosts: slaves
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - dockerSwarmSlave